In [ ]:
#Importando bibliotecas e criando a conexão com o SQLite3
import pandas as pd
from sqlite3 import connect
conn = connect(":memory:")

In [ ]:
#Lendo os arquivos .csv e concatenando, uma vez que não usaremos técnicas de ML com divisão train e test
df_train = pd.read_csv('/content/sample_data/train.csv')
df_test = pd.read_csv('/content/sample_data/test.csv')
df = pd.concat([df_train, df_test])

In [ ]:
df.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [ ]:
#Checando se existem valores nulos nos dados
print('Número de valores total: ', df.shape[0])
print('           Coluna         |   N° de valores nulos\n')
df.isna().sum()

Número de valores total:  129880
           Coluna         |   N° de valores nulos

Unnamed: 0                             0
id                                     0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             393
satisfaction                           0
dtype: int64

In [ ]:
#Substituindo os valores nulos nos dados pela mediana da coluna
df['Arrival Delay in Minutes'] = df['Arrival Delay in Minutes'].fillna(df['Arrival Delay in Minutes'].median(axis = 0))

In [ ]:
#Confirmando que os valores foram substituidos
print('Número de valores total: ', df.shape[0])
print('           Coluna         |   N° de valores nulos\n')
df.isna().sum()

Número de valores total:  129880
           Coluna         |   N° de valores nulos

Unnamed: 0                           0
id                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
satisfaction                         0
dtype: int64

In [ ]:
#Checando número de linhas duplicadas
print('Número de linhas duplicadas: ', df.duplicated().sum())

Número de linhas duplicadas:  0

In [ ]:
#Calculando a maior e a menor idade nos dados, para criamos os bins
print('A maior idade nos dados é: ', df['Age'].max())
print('A menor idade nos dados é: ', df['Age'].min())

A maior idade nos dados é:  85
A menor idade nos dados é:  7

In [ ]:
#Criando a coluna de idade com bins (categorias)
df['Age_bin'] = pd.cut(df['Age'], bins=[0, 20, 30, 40, 50, 60, 70, 80, 90], labels = ["0-20", "21-30", "31-40", "41-50", "51-60", "61-70", "71-80", "81-90"])

In [ ]:
#Conferindo se nossos bins de idade foram criados corretamente
df['Age_bin'].value_counts()

Age_bin
41-50    29006
21-30    26822
31-40    26392
51-60    23548
0-20     14058
61-70     9090
71-80      939
81-90       25
Name: count, dtype: int64

In [ ]:
#Calculando a maior e a menor distância de viagem nos dados, para criamos os bins
print('A maior distância de viagem nos dados é: ', df['Flight Distance'].max())
print('A menor distância de viagem nos dados é: ', df['Flight Distance'].min())

A maior distância de viagem nos dados é:  4983
A menor distância de viagem nos dados é:  31

In [ ]:
#Criando a coluna de distância de viagem com bins (categorias)
df['Distance_bins'] = pd.cut(df['Flight Distance'], bins=[0, 500, 1500, 3000, 4500, 6000], labels = ["0-500", "501-1500", "1501-3000", "3001-4500", "4501-6000"])

In [ ]:
#Conferindo se nossos bins de distância foram criados corretamente
df['Distance_bins'].value_counts()

Distance_bins
501-1500     50252
0-500        40276
1501-3000    29039
3001-4500    10258
4501-6000       55
Name: count, dtype: int64

In [ ]:
#Calculando o maior e o menor atraso na decolagem nos dados, para criamos os bins
print('O maior atraso na decolagem, em minutos, nos dados é: ', df['Departure Delay in Minutes'].max())
print('O menor atraso na decolagem, em minutos, nos dados é: ', df['Departure Delay in Minutes'].min())

O maior atraso na decolagem, em minutos, nos dados é:  1592
O menor atraso na decolagem, em minutos, nos dados é:  0

In [ ]:
#Criando a coluna de atraso na decolagem com bins (categorias)
df['Departure_bins'] = pd.cut(df['Departure Delay in Minutes'], bins=[0, 1, 120, 240, 480, 840, 1200, 1800], labels = ["Sem atraso","Até 2 horas", "2-4 horas", "4-8 horas", "8-14 horas", "14-20 horas", "+20 horas"], include_lowest=True)

In [ ]:
#Conferindo se nossos bins de atraso na decolag foram criados corretamente
df['Distance_bins'].value_counts()

Distance_bins
501-1500     50252
0-500        40276
1501-3000    29039
3001-4500    10258
4501-6000       55
Name: count, dtype: int64

In [ ]:
#Calculando o maior e o menor atraso na chegada nos dados, para criamos os bins
print('O maior atraso na chegada, em minutos, nos dados é: ', df['Arrival Delay in Minutes'].max())
print('O menor atraso na chegada, em minutos, nos dados é: ', df['Arrival Delay in Minutes'].min())

O maior atraso na chegada, em minutos, nos dados é:  1584.0
O menor atraso na chegada, em minutos, nos dados é:  0.0

In [ ]:
#Criando a coluna de atraso na chegada com bins (categorias)
df['Arrival_bins'] = pd.cut(df['Arrival Delay in Minutes'], bins=[0, 1, 120, 240, 480, 840, 1200, 1800], labels = ["Sem atraso","Até 2 horas", "2-4 horas", "4-8 horas", "8-14 horas", "14-20 horas", "+20 horas"], include_lowest=True)

In [ ]:
#Conferindo se nossos bins de atraso na chegada foram criados corretamente
df['Arrival_bins'].value_counts()

Arrival_bins
Sem atraso     75893
Até 2 horas    50795
2-4 horas       2576
4-8 horas        566
8-14 horas        40
14-20 horas        8
+20 horas          2
Name: count, dtype: int64

O atraso na decolagem está correlacionado com o atraso na chegada. Se o avião decolou atrasado, ele irá provavelmente aterrisar atrasado. Queremos observar se a satisfação do cliente é alterada se o atraso ocorre somente na chegada, e não na decolagem. Chamaremos esta variável de Atraso de Percurso, uma vez que estamos lidando com atrasos que foram causados durante o voo. Valores positivos nesta variável indicam que houve atraso no percurso. Valores negativos indicam que o percurso foi mais rápido do que o esperado e "compensou" parte do atraso na decolagem.

In [ ]:
df['Flight Delay in Minutes'] = df['Arrival Delay in Minutes'] - df['Departure Delay in Minutes']

In [ ]:
print('O maior atraso de percurso, em minutos, nos dados é: ', df['Flight Delay in Minutes'].max())
print('O menor atraso de percurso, em minutos, nos dados é: ', df['Flight Delay in Minutes'].min())

O maior atraso de percurso, em minutos, nos dados é:  234.0
O menor atraso de percurso, em minutos, nos dados é:  -530.0

In [ ]:
#Convertendo todos as colunas para letras minúsculas e os espaços para _, para facilitar a leitura em SQL
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df.columns = df.columns.str.replace('/', '_')
df.columns = df.columns.str.replace('-', '_')

In [ ]:
#Convertendo dataframe em SQL
df.to_sql(name="data", con=conn)
pd.read_sql("SELECT * FROM data LIMIT 5", con = conn)

,index,unnamed:_0,id,gender,customer_type,age,type_of_travel,class,flight_distance,inflight_wifi_service,...,inflight_service,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,satisfaction,age_bin,distance_bins,departure_bins,arrival_bins,flight_delay_in_minutes
0,0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,...,5,5,25,18.0,neutral or dissatisfied,0-20,0-500,Até 2 horas,Até 2 horas,-7.0
1,1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,...,4,1,1,6.0,neutral or dissatisfied,21-30,0-500,Sem atraso,Até 2 horas,5.0
2,2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,...,4,5,0,0.0,satisfied,21-30,501-1500,Sem atraso,Sem atraso,0.0
3,3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,...,4,2,11,9.0,neutral or dissatisfied,21-30,501-1500,Até 2 horas,Até 2 horas,-2.0
4,4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,...,3,3,0,0.0,satisfied,61-70,0-500,Sem atraso,Sem atraso,0.0

#Análise Exploratória dos Dados

In [ ]:
#Relação entre gênero e satisfação
pd.read_sql("SELECT Gender, satisfaction, COUNT(*) AS num_of_passengers, COUNT(*) * 100.0 / (SELECT COUNT(*) FROM data) AS percentage_of_total FROM data GROUP BY Gender, satisfaction", con=conn)

   gender             satisfaction  num_of_passengers  percentage_of_total
0  Female  neutral or dissatisfied              37630            28.972898
1  Female                satisfied              28269            21.765476
2    Male  neutral or dissatisfied              35822            27.580844
3    Male                satisfied              28159            21.680782

In [ ]:
#Relação entre tipo de cliente e satisfação
pd.read_sql("SELECT customer_type, satisfaction, COUNT(*) AS num_of_passengers, COUNT(*) * 100.0 / (SELECT COUNT(*) FROM data) AS percentage_of_total FROM data GROUP BY customer_type, satisfaction", con=conn)

,customer_type,satisfaction,num_of_passengers,percentage_of_total
0,Loyal Customer,neutral or dissatisfied,55372,42.633200
1,Loyal Customer,satisfied,50728,39.057592
2,disloyal Customer,neutral or dissatisfied,18080,13.920542
3,disloyal Customer,satisfied,5700,4.388666

In [ ]:
#Relação entre classe e satisfação
pd.read_sql("SELECT class, satisfaction, COUNT(*) AS num_of_passengers, COUNT(*) * 100.0 / (SELECT COUNT(*) FROM data) AS percentage_of_total FROM data GROUP BY class, satisfaction", con=conn)

      class             satisfaction  num_of_passengers  percentage_of_total
0  Business  neutral or dissatisfied              18994            14.624269
1  Business                satisfied              43166            33.235294
2       Eco  neutral or dissatisfied              47366            36.469048
3       Eco                satisfied              10943             8.425470
4  Eco Plus  neutral or dissatisfied               7092             5.460425
5  Eco Plus                satisfied               2319             1.785494

In [ ]:
#Relação entre tipo de viagem e satisfação
pd.read_sql("SELECT type_of_travel, satisfaction, COUNT(*) AS num_of_passengers, COUNT(*) * 100.0 / (SELECT COUNT(*) FROM data) AS percentage_of_total FROM data GROUP BY type_of_travel, satisfaction", con=conn)

,type_of_travel,satisfaction,num_of_passengers,percentage_of_total
0,Business travel,neutral or dissatisfied,37337,28.747305
1,Business travel,satisfied,52356,40.311056
2,Personal Travel,neutral or dissatisfied,36115,27.806437
3,Personal Travel,satisfied,4072,3.135202

In [ ]:
#Relação entre idade e satisfação
pd.read_sql("SELECT age_bin, satisfaction, COUNT(*) AS num_of_passengers, COUNT(*) * 100.0 / (SELECT COUNT(*) FROM data) AS percentage_of_total FROM data GROUP BY age_bin, satisfaction", con=conn)

   age_bin             satisfaction  num_of_passengers  percentage_of_total
0     0-20  neutral or dissatisfied              11255             8.665691
1     0-20                satisfied               2803             2.158146
2    21-30  neutral or dissatisfied              17051            13.128272
3    21-30                satisfied               9771             7.523098
4    31-40  neutral or dissatisfied              14934            11.498306
5    31-40                satisfied              11458             8.821990
6    41-50  neutral or dissatisfied              12203             9.395596
7    41-50                satisfied              16803            12.937327
8    51-60  neutral or dissatisfied              10048             7.736372
9    51-60                satisfied              13500            10.394210
10   61-70  neutral or dissatisfied               7283             5.607484
11   61-70                satisfied               1807             1.391284
12   71-80  neutral or dissatisfied                659             0.507391
13   71-80                satisfied                280             0.215584
14   81-90  neutral or dissatisfied                 19             0.014629
15   81-90                satisfied                  6             0.004620

In [ ]:
#Relação entre distância e satisfação
pd.read_sql("SELECT distance_bins, satisfaction, COUNT(*) AS num_of_passengers, COUNT(*) * 100.0 / (SELECT COUNT(*) FROM data) AS percentage_of_total FROM data GROUP BY distance_bins, satisfaction", con=conn)

,distance_bins,satisfaction,num_of_passengers,percentage_of_total
0,0-500,neutral or dissatisfied,26759,20.602864
1,0-500,satisfied,13517,10.407299
2,1501-3000,neutral or dissatisfied,11027,8.490145
3,1501-3000,satisfied,18012,13.868186
4,3001-4500,neutral or dissatisfied,2311,1.779335
5,3001-4500,satisfied,7947,6.118725
6,4501-6000,neutral or dissatisfied,25,0.019249
7,4501-6000,satisfied,30,0.023098
8,501-1500,neutral or dissatisfied,33330,25.662150
9,501-1500,satisfied,16922,13.028950

In [ ]:
#Relação entre atraso na decolagem e satisfação
pd.read_sql("SELECT departure_bins, satisfaction, COUNT(*) AS num_of_passengers, COUNT(*) * 100.0 / (SELECT COUNT(*) FROM data) AS percentage_of_total FROM data GROUP BY departure_bins, satisfaction", con=conn)

,departure_bins,satisfaction,num_of_passengers,percentage_of_total
0,+20 horas,neutral or dissatisfied,1,0.000770
1,+20 horas,satisfied,1,0.000770
2,14-20 horas,neutral or dissatisfied,6,0.004620
3,14-20 horas,satisfied,3,0.002310
4,2-4 horas,neutral or dissatisfied,1606,1.236526
5,2-4 horas,satisfied,896,0.689868
6,4-8 horas,neutral or dissatisfied,343,0.264090
7,4-8 horas,satisfied,200,0.153988
8,8-14 horas,neutral or dissatisfied,25,0.019249
9,8-14 horas,satisfied,12,0.009239
10,Até 2 horas,neutral or dissatisfied,29769,22.920388
11,Até 2 horas,satisfied,19980,15.383431
12,Sem atraso,neutral or dissatisfied,41702,32.108100
13,Sem atraso,satisfied,35336,27.206652

In [ ]:
#Relação entre atraso na chegada e satisfação
pd.read_sql("SELECT arrival_bins, satisfaction, COUNT(*) AS num_of_passengers, COUNT(*) * 100.0 / (SELECT COUNT(*) FROM data) AS percentage_of_total FROM data GROUP BY arrival_bins, satisfaction", con=conn)

,arrival_bins,satisfaction,num_of_passengers,percentage_of_total
0,+20 horas,neutral or dissatisfied,1,0.000770
1,+20 horas,satisfied,1,0.000770
2,14-20 horas,neutral or dissatisfied,5,0.003850
3,14-20 horas,satisfied,3,0.002310
4,2-4 horas,neutral or dissatisfied,1660,1.278103
5,2-4 horas,satisfied,916,0.705266
6,4-8 horas,neutral or dissatisfied,348,0.267940
7,4-8 horas,satisfied,218,0.167847
8,8-14 horas,neutral or dissatisfied,26,0.020018
9,8-14 horas,satisfied,14,0.010779
10,Até 2 horas,neutral or dissatisfied,31504,24.256237
11,Até 2 horas,satisfied,19291,14.852941
12,Sem atraso,neutral or dissatisfied,39908,30.726825
13,Sem atraso,satisfied,35985,27.706344

In [ ]:
#Relação de gênero e satisfação com convêniencia do tempo
pd.read_sql("SELECT gender, satisfaction, AVG(departure_arrival_time_convenient) AS avg_rating_convenience FROM data GROUP BY gender, satisfaction", con=conn)

   gender             satisfaction  avg_rating_convenience
0  Female  neutral or dissatisfied                3.105501
1  Female                satisfied                2.962291
2    Male  neutral or dissatisfied                3.156189
3    Male                satisfied                2.963848

In [ ]:
#Relação de gênero e satisfação com compra de passagem online
pd.read_sql("SELECT gender, satisfaction, AVG(ease_of_online_booking) AS avg_rating_online FROM data GROUP BY gender, satisfaction", con=conn)

   gender             satisfaction  avg_rating_online
0  Female  neutral or dissatisfied           2.544247
1  Female                satisfied           3.020942
2    Male  neutral or dissatisfied           2.554799
3    Male                satisfied           3.032991

In [ ]:
#Relação de gênero e satisfação com localização do portão de embarque
pd.read_sql("SELECT gender, satisfaction, AVG(gate_location) AS avg_rating_location FROM data GROUP BY gender, satisfaction", con=conn)

   gender             satisfaction  avg_rating_location
0  Female  neutral or dissatisfied             2.985517
1  Female                satisfied             2.968022
2    Male  neutral or dissatisfied             2.974317
3    Male                satisfied             2.977698

In [ ]:
#Relação de gênero e satisfação com comida e bebida no voo
pd.read_sql("SELECT gender, satisfaction, AVG(food_and_drink) AS avg_rating_food FROM data GROUP BY gender, satisfaction", con=conn)

   gender             satisfaction  avg_rating_food
0  Female  neutral or dissatisfied         2.993622
1  Female                satisfied         3.480562
2    Male  neutral or dissatisfied         2.921445
3    Male                satisfied         3.570510

In [ ]:
#Relação de gênero e satisfação com checkin online
pd.read_sql("SELECT gender, satisfaction, AVG(online_boarding) AS avg_rating_online_checkin FROM data GROUP BY gender, satisfaction", con=conn)

   gender             satisfaction  avg_rating_online_checkin
0  Female  neutral or dissatisfied                   2.811135
1  Female                satisfied                   3.980013
2    Male  neutral or dissatisfied                   2.498409
3    Male                satisfied                   4.071878

In [ ]:
#Relação de gênero e satisfação com o conforto do assento
pd.read_sql("SELECT gender, satisfaction, AVG(seat_comfort) AS avg_rating_comfort FROM data GROUP BY gender, satisfaction", con=conn)

   gender             satisfaction  avg_rating_comfort
0  Female  neutral or dissatisfied            3.140420
1  Female                satisfied            3.935159
2    Male  neutral or dissatisfied            2.930406
3    Male                satisfied            3.997798

In [ ]:
#Relação de gênero e satisfação com o entreterimento ofertado no voo
pd.read_sql("SELECT gender, satisfaction, AVG(inflight_entertainment) AS avg_rating_entertainment FROM data GROUP BY gender, satisfaction", con=conn)

   gender             satisfaction  avg_rating_entertainment
0  Female  neutral or dissatisfied                  2.898618
1  Female                satisfied                  3.957904
2    Male  neutral or dissatisfied                  2.885936
3    Male                satisfied                  3.970525

In [ ]:
#Relação de gênero e satisfação com o serviço ofertado no voo
pd.read_sql("SELECT gender, satisfaction, AVG(on_board_service) AS avg_rating_service FROM data GROUP BY gender, satisfaction", con=conn)

   gender             satisfaction  avg_rating_service
0  Female  neutral or dissatisfied            2.984640
1  Female                satisfied            3.894266
2    Male  neutral or dissatisfied            3.056195
3    Male                satisfied            3.817927

In [ ]:
#Relação de gênero e satisfação com o espaço para as pernas
pd.read_sql("SELECT gender, satisfaction, AVG(leg_room_service) AS avg_rating_leg_room FROM data GROUP BY gender, satisfaction", con=conn)

   gender             satisfaction  avg_rating_leg_room
0  Female  neutral or dissatisfied             2.886420
1  Female                satisfied             3.875270
2    Male  neutral or dissatisfied             3.099715
3    Male                satisfied             3.764622

In [ ]:
#Relação de gênero e satisfação com o tratamento das bagagens
pd.read_sql("SELECT gender, satisfaction, AVG(baggage_handling) AS avg_rating_baggage FROM data GROUP BY gender, satisfaction", con=conn)

   gender             satisfaction  avg_rating_baggage
0  Female  neutral or dissatisfied            3.284427
1  Female                satisfied            3.996392
2    Male  neutral or dissatisfied            3.469963
3    Male                satisfied            3.937320

In [ ]:
#Relação de gênero e satisfação com o checkin presencial
pd.read_sql("SELECT gender, satisfaction, AVG(checkin_service) AS avg_checkin FROM data GROUP BY gender, satisfaction", con=conn)

   gender             satisfaction  avg_checkin
0  Female  neutral or dissatisfied     3.032660
1  Female                satisfied     3.645866
2    Male  neutral or dissatisfied     3.053794
3    Male                satisfied     3.652154

In [ ]:
#Relação de gênero e satisfação com o serviço geral
pd.read_sql("SELECT gender, satisfaction, AVG(inflight_service) AS avg_inflight FROM data GROUP BY gender, satisfaction", con=conn)

   gender             satisfaction  avg_inflight
0  Female  neutral or dissatisfied      3.296067
1  Female                satisfied      3.998868
2    Male  neutral or dissatisfied      3.487857
3    Male                satisfied      3.943002

In [ ]:
#Relação de gênero e satisfação com a limpeza
pd.read_sql("SELECT gender, satisfaction, AVG(cleanliness) AS avg_cleanliness FROM data GROUP BY gender, satisfaction", con=conn)

   gender             satisfaction  avg_cleanliness
0  Female  neutral or dissatisfied         2.967526
1  Female                satisfied         3.702041
2    Male  neutral or dissatisfied         2.896321
3    Male                satisfied         3.791150

In [ ]:
#Para facilitar a visualização no Power BI, criamos uma tabela de clientes satisfeitos e uma de clientes dessatisfeitos
satisfied = df[df['satisfaction'] == 'satisfied']
dissatisfied = df[df['satisfaction'] == 'dissatisfied']

In [ ]:
#Salvando as tabelas novas em formato csv
satisfied.to_csv('satisfied.csv', index=False)
dissatisfied.to_csv('dissatisfied.csv', index=False)

In [ ]:
#Salvando o dataframe total, com as alterações feitas, em csv
df.to_csv('data.csv', index=False)